databases:
  - name: banking-postgres
    databaseName: bank
    user: bankuser
    plan: free

services:
  # Unified Banking System (Backend + Frontend)
  - type: web
    name: banking-system
    env: node
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: banking-postgres
          property: connectionString
      - key: JWT_SECRET
        value: banking_system_super_secure_jwt_key_2024_production_render_deployment
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      - key: CORS_ORIGIN
        value: "*"
      - key: REACT_APP_API_URL
        value: /api

