databases:
  - name: banking-postgres
    databaseName: bank
    user: bankuser
    plan: free

services:
  # Backend API Service
  - type: web
    name: banking-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: banking-postgres
          property: connectionString
      - key: JWT_SECRET
        value: banking_system_super_secure_jwt_key_2024_production_render_deployment
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      - key: CORS_ORIGIN
        value: https://banking-frontend.onrender.com

  # Frontend React App
  - type: web
    name: banking-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://banking-backend.onrender.com/api

